[versions]
detekt = "1.23.7"  # Note: Plugin versions must be updated in the settings.gradle.kts too
kotlin = "2.0.20"  # Note: Plugin versions must be updated in the settings.gradle.kts too

groovy = "3.0.22"
jansi = "2.4.1"
kx-ser = "1.7.2"
logback = "1.5.7"
logback-groovy = "1.14.5"
logging = "7.0.0"

[libraries]
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
groovy = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
jansi = { module = "org.fusesource.jansi:jansi", version.ref = "jansi" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
kx-ser = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kx-ser" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
logback-groovy = { module = "io.github.virtualdogbert:logback-groovy-config", version.ref = "logback-groovy" }
logging = { module = "io.github.oshai:kotlin-logging", version.ref = "logging" }
